# Generated by Django 5.1.3 on 2026-01-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_feedback_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemList',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='booktable',
            name='Phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
